source/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('registration/', views.register_view, name='register'),
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('user/<int:pk>/update/', views.UserPersonalInfoChangeView.as_view(), name='user_update_info'),
    path('user/<int:pk>/password_change/', views.UserPasswordChangeView.as_view(), name='user_change_password'),
    path('users/', views.UserListView.as_view(), name='users_list'),
]

source/api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from api import views


router = routers.DefaultRouter()
router.register(r'issues', views.IssueViewSet)
router.register(r'projects', views.ProjectViewSet)

app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='api_auth_token'),
    path('logout/', views.LogoutView.as_view(), name='delete_auth_token'),
    path('requests/', views.requests_view, name='requests'),
]

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('issue/<int:pk>', views.IssueView.as_view(), name='issue_detail'),
    path('issue/create/', views.IssueCreateView.as_view(), name='create_issue'),
    path('issue/update/<int:pk>', views.IssueUpdateView.as_view(), name='update_issue'),
    path('issue/delete/<int:pk>', views.IssueDeleteView.as_view(), name='delete_issue'),
    path('statuses/', views.StatusView.as_view(), name='statuses_list'),
    path('types/', views.TypeView.as_view(), name='types_list'),
    path('status/delete/<int:pk>', views.StatusDeleteView.as_view(), name='delete_status'),
    path('type/delete/<int:pk>', views.TypeDeleteView.as_view(), name='delete_type'),
    path('status/create/', views.StatusCreateView.as_view(), name='create_status'),
    path('type/create/', views.TypeCreateView.as_view(), name='create_type'),
    path('status/update/<int:pk>', views.StatusUpdateView.as_view(), name='update_status'),
    path('type/update/<int:pk>', views.TypeUpdateView.as_view(), name='update_type'),
    path('projects/', views.ProjectView.as_view(), name='projects_list'),
    path('project/<int:pk>', views.ProjectDetailView.as_view(), name='project_detail'),
    path('project/create', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/delete/<int:pk>', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/update/<int:pk>', views.ProjectUpdateView.as_view(), name='update_project'),
    path('project/add-issue/<int:pk>', views.ProjectCreateIssueView.as_view(), name='create_project_issue'),
    path('project/add-users/<int:pk>', views.AddProjectUsers.as_view(), name='add_project_users'),
    path('project/delete-user/<int:pk>', views.DeleteProjectUser.as_view(), name='delete_project_user'),
]

source/accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pict', verbose_name='Аватар')
    about_user = models.TextField(max_length=500, null=True, blank=True, verbose_name='О себе')
    link_to_github = models.URLField(max_length=100, null=True, blank=True, verbose_name='Ссылка на github')

    def __str__(self):
        return self.user.get_full_name() + 'профиль'

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

source/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import requests

from accounts.models import Profile


class UserCreationForm(forms.Form):
    username = forms.CharField(max_length=100, label='Логин', required=True)
    password = forms.CharField(max_length=100, label='Пароль', required=True,
                               widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=100, label='Подтверждение пароля', required=True,
                                       widget=forms.PasswordInput)
    first_name = forms.CharField(max_length=100, required=False, label='Имя')
    last_name = forms.CharField(max_length=100, required=False, label='Фамилия')
    email = forms.EmailField(required=True)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            User.objects.get(username=username)
            raise ValidationError('Такой пользователь уже существует',
                                  code='user_exists')
        except User.DoesNotExist:
            return username

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data['password']
        password_2 = self.cleaned_data['password_confirm']
        first_name = self.cleaned_data['first_name']
        last_name = self.cleaned_data['last_name']
        if password_1 != password_2:
            raise ValidationError('Пароли не совпадают',
                                  code='passwords_do_not_match')
        elif not first_name and not last_name:
            raise ValidationError('Имя или Фамилия должны быть заполнены',
                                  code='first_name and last_name_exists')

        return self.cleaned_data


class UserChangeForm(forms.ModelForm):
    avatar = forms.ImageField(required=False, label='Аватар')
    about_user = forms.CharField(required=False, widget=forms.Textarea, label='О себе')
    link_to_github = forms.URLField(required=False, label='Ссылка на Github')

    def get_initial_for_field(self, field, field_name):
        if field_name in self.Meta.profile_fields:
            return getattr(self.instance.profile, field_name)
        return super().get_initial_for_field(field, field_name)

    def save(self, commit=True):
        user = super().save(commit=commit)
        user.profile = self.save_profile(commit)
        return user

    def save_profile(self, commit=True):
        profile, _ = Profile.objects.get_or_create(user=self.instance)
        for field in self.Meta.profile_fields:
            setattr(profile, field, self.cleaned_data.get(field))
        if not profile.avatar:
            profile.avatar = None
        if commit:
            profile.save()
        return profile

    def clean_link_to_github(self):
        link_to_github = self.cleaned_data.get('link_to_github')
        if link_to_github:
            request = requests.get(link_to_github)

            if not request.status_code == 200 or 'github.com' not in link_to_github:
                raise ValidationError('Неверная ссылка или такого профиля не существует',
                                      code='link_to_github_exists')
        return link_to_github

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        profile_fields = ['about_user', 'link_to_github', 'avatar']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label='Новый пароль', strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Подтвержение пароля', strip=False, widget=forms.PasswordInput)
    old_password = forms.CharField(label='Старый пароль', strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if password != password_confirm:
            raise ValidationError('Пароли не совпадают')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise ValidationError('Неверный старый пароль')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import DetailView, UpdateView, ListView

from accounts.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from accounts.models import Profile


def login_view(request):
    context = {}
    next_page = request.GET.get('next')
    url = request.session.setdefault('url', next_page)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if url:
                return redirect(url)
            return redirect('webapp:index')
        else:
            context['has_error'] = True
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:index')


def register_view(request):
    if request.method == 'GET':
        form = UserCreationForm()
        return render(request, 'register.html', {'form': form})
    elif request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = User(username=form.cleaned_data['username'],
                        first_name=form.cleaned_data['first_name'],
                        last_name=form.cleaned_data['last_name'],
                        email=form.cleaned_data['email'])
            user.set_password(form.cleaned_data['password'])
            user.save()
            Profile.objects.create(user=user)
            login(request, user)
            return redirect("webapp:index")
        else:
            return render(request, 'register.html', {'form': form})


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


class UserPersonalInfoChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_info_change.html'
    form_class = UserChangeForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user.pk == self.kwargs['pk']

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user.pk == self.kwargs['pk']

    def get_success_url(self):
        return reverse('accounts:login')


class UserListView(ListView):
    model = User
    template_name = 'users_list.html'
    context_object_name = 'persons'

source/accounts/templates/login.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Пример на bootstrap 4: Пользовательская форма и дизайн для простой формы входа.">

    <title>Страница входа</title>

    {% load static %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">


    <style>
        html,
        body {
            height: 100%;
        }

        body {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-align: center;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }

        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }

        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>

</head>

<body class="text-center">

<form class="form-signin" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Вход</h1>
    {% if has_error %}
        <div class="alert alert-danger" role="alert">
            Неверный логин или пароль
        </div>
    {% endif %}
    <label for="username" class="sr-only"></label>
    <input type="text" id="username" class="form-control" placeholder="Логин" required autofocus
           name="username">
    <label for="password" class="sr-only">Password</label>
    <input type="password" id="password" class="form-control" placeholder="Пароль" required name="password">
    <button class="btn btn-lg btn-primary btn-block mb-3" type="submit">войти</button>
    <a href="{% url 'webapp:index' %}">На главную</a>
    <p class="mt-5 mb-3 text-muted">&copy; Трекер задач 2019</p>
</form>
</body>
</html>

source/accounts/templates/register.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    Регистрация
{% endblock %}

{% block body %}
    <style>
        body {
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>

    <form action="{% url 'accounts:register' %}" method="post" class="form-signin text-center">
        {% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Регистрация</h1>
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
        {% for field in form %}
            <label for="{{ field.id_for_label }}" class="form-label mt-2 mb-0
            {% if field.field.required %}required{% endif %}">{{ field.label }}</label>
            {% if field.errors %}
                {{ field|add_class:'form-control' }}
                {% for error in field.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endfor %}
            {% else %}
                {% if forloop.first %}
                    {{ field|add_class:"form-control" |attr:"autofocus" }}
                {% else %}
                    {{ field|add_class:"form-control" }}
                {% endif %}
            {% endif %}
        {% endfor %}

        <button class="btn btn-lg btn-primary btn-block mt-3" type="submit">отправить</button>
        <p class="mt-5 mb-3 text-muted">&copy; Трекер задач 2019</p>
    </form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ user_obj }}
{% endblock %}

{% block body %}
    <h1>Личный кабинет</h1>
    <div class="card mb-3" style="max-width: 640px;">
        <div class="row no-gutters">
            <div class="col-md-4">
                {% if user_obj.profile.avatar %}
                    <img src="{{ user_obj.profile.avatar.url }}" class="card-img" alt="user-foto">
                {% else %}
                    <img src="{% static 'images/no_foto.png' %}" class="card-img" alt="user-foto">
                {% endif %}

            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Пользователь: {{ user_obj.username }}</h5>
                    <p>Имя: <b>{{ user_obj.first_name }}</b></p>
                    <p>Фамилия: <b>{{ user_obj.last_name }}</b></p>
                    <p>О себе: <b>{{ user_obj.profile.about_user|default_if_none:'' }}</b></p>
                    <p>Почта: <b>{{ user_obj.email }}</b></p>
                    <p>Ссылка на github: <a href="{{ user_obj.profile.link_to_github }}" target="_blank">{{ user_obj.profile.link_to_github|default_if_none:'' }}</a></p>
                    <p>Дата регистрации: <b>{{ user_obj.date_joined }}</b></p>
                    <p class="card-text"><small class="text-muted">Последний вход {{ user_obj.last_login }}</small></p>
                </div>
            </div>
        </div>
    </div>

    {% if user.pk == user_obj.pk %}
        <a href="{% url 'accounts:user_update_info' user_obj.pk %}" class="btn btn-primary">Редактировать</a>
        <a href="{% url 'accounts:user_change_password' user_obj.pk %}" class="btn btn-secondary">Сменить пароль</a>
    {% endif %}

{% endblock %}

source/accounts/templates/user_info_change.html
{% extends 'base.html' %}

{% block title %}
    Редактировать пользователя
{% endblock %}

{% block body %}
<h1>Личный кабинет</h1>
    <h4>Редактировать личные данные</h4>
    <form action="{% url "accounts:user_update_info" user_obj.pk %}" method="post" class="jumbotron" enctype="multipart/form-data">
        {% include 'partial/issue_form.html' with button_text='Редактировать' %}
    </form>
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}

{% block title %}
    Смена пароля
{% endblock %}

{% block body %}
<h1>Личный кабинет</h1>
    <h4>Смена пароля</h4>
    <form action="{% url "accounts:user_change_password" user_obj.pk %}" method="post" class="jumbotron">
        {% include 'partial/issue_form.html' with button_text='Отправить' %}
    </form>
{% endblock %}

source/accounts/templates/users_list.html
{% extends 'base.html' %}

{% block title %}Пользователи{% endblock %}

{% block body %}
    <h3 class="text-center">Пользователи</h3>
    <ul class="list-group">
        {% for person in persons %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {% if person.pk == user.pk %}
                    <span class="text-danger">{{ person }}</span>
                    {% else %}
                    {{ person }}
                {% endif %}
                    <span class="badge badge-pill bg-light">
                    <a href="{% url 'accounts:user_detail' person.pk %}" class="btn text-info">Просмотр</a>
                </span>
            </li>
        {% endfor %}
    </ul>
{% endblock %}