source/api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from api import views


router = routers.DefaultRouter()
router.register(r'issues', views.IssueViewSet)
router.register(r'projects', views.ProjectViewSet)

app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='api_auth_token'),
    path('logout/', views.LogoutView.as_view(), name='delete_auth_token'),
    path('requests/', views.requests_view, name='requests'),
]

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('issue/<int:pk>', views.IssueView.as_view(), name='issue_detail'),
    path('issue/create/', views.IssueCreateView.as_view(), name='create_issue'),
    path('issue/update/<int:pk>', views.IssueUpdateView.as_view(), name='update_issue'),
    path('issue/delete/<int:pk>', views.IssueDeleteView.as_view(), name='delete_issue'),
    path('statuses/', views.StatusView.as_view(), name='statuses_list'),
    path('types/', views.TypeView.as_view(), name='types_list'),
    path('status/delete/<int:pk>', views.StatusDeleteView.as_view(), name='delete_status'),
    path('type/delete/<int:pk>', views.TypeDeleteView.as_view(), name='delete_type'),
    path('status/create/', views.StatusCreateView.as_view(), name='create_status'),
    path('type/create/', views.TypeCreateView.as_view(), name='create_type'),
    path('status/update/<int:pk>', views.StatusUpdateView.as_view(), name='update_status'),
    path('type/update/<int:pk>', views.TypeUpdateView.as_view(), name='update_type'),
    path('projects/', views.ProjectView.as_view(), name='projects_list'),
    path('project/<int:pk>', views.ProjectDetailView.as_view(), name='project_detail'),
    path('project/create', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/delete/<int:pk>', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/update/<int:pk>', views.ProjectUpdateView.as_view(), name='update_project'),
    path('project/add-issue/<int:pk>', views.ProjectCreateIssueView.as_view(), name='create_project_issue'),
    path('project/add-users/<int:pk>', views.AddProjectUsers.as_view(), name='add_project_users'),
    path('project/delete-user/<int:pk>', views.DeleteProjectUser.as_view(), name='delete_project_user'),
]

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models

PROJECT_STATUS_ACTIVE = 'active'
PROJECT_STATUS_BLOCKED = 'blocked'
PROJECT_STATUS_CHOICES = (
    (PROJECT_STATUS_ACTIVE, 'Активен'),
    (PROJECT_STATUS_BLOCKED, 'Заблокирован')
)


class Issue(models.Model):
    summary = models.CharField(max_length=60, verbose_name='Краткое описание')
    description = models.TextField(max_length=400, null=True, blank=True, verbose_name='Полное описание')
    status = models.ForeignKey('webapp.Status', related_name='issues', on_delete=models.PROTECT, verbose_name='Статус')
    type = models.ForeignKey('webapp.Type', related_name='issues', on_delete=models.PROTECT, verbose_name='Тип')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    project = models.ForeignKey('webapp.Project', related_name='issues', on_delete=models.PROTECT, verbose_name='Проект')
    created_by = models.ForeignKey(User, related_name='created_issues', on_delete=models.PROTECT, verbose_name='Создатель')
    assigned_to = models.ForeignKey(User, related_name='assigned_issues', on_delete=models.PROTECT, verbose_name='Исполнитель')

    def __str__(self):
        return self.summary

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'
        permissions = [
            ('can_add_issue_for_project', 'Может добавлять задачи к проекту')
        ]


class Status(models.Model):
    name = models.CharField(max_length=20, verbose_name='Статус')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Статус задачи'
        verbose_name_plural = 'Статусы задач'


class Type(models.Model):
    name = models.CharField(max_length=20, verbose_name='Тип')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тип задачи'
        verbose_name_plural = 'Типы задач'


class Project(models.Model):
    summary = models.CharField(max_length=60, verbose_name='Название')
    description = models.TextField(max_length=400, null=True, blank=True, verbose_name='Описание')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    status = models.CharField(max_length=20, choices=PROJECT_STATUS_CHOICES, default=PROJECT_STATUS_ACTIVE, verbose_name='Статус')

    def __str__(self):
        return self.summary

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'


class Team(models.Model):
    user = models.ForeignKey(User, related_name='teams', on_delete=models.PROTECT, verbose_name='Пользователь')
    project = models.ForeignKey('webapp.Project', related_name='teams', on_delete=models.PROTECT, verbose_name='Проект')
    start_date = models.DateField(null=True, blank=True, verbose_name='Дата начала работы ')
    end_date = models.DateField(null=True, blank=True, verbose_name='Дата окончания работы')

    def __str__(self):
        return f'{self.user.username} - {self.project.summary}'

    class Meta:
        verbose_name = 'Команда'
        verbose_name_plural = 'Команды'

source/webapp/forms.py
from django import forms
from django.contrib.auth.models import User

from webapp.models import Issue, Status, Type, Project


class IssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        exclude = ['create_date', 'created_by']


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['name']


class TypeForm(forms.ModelForm):
    class Meta:
        model = Type
        fields = ['name']


class ProjectForm(forms.ModelForm):
    users = forms.ModelMultipleChoiceField(queryset=User.objects.all(), required=False)

    class Meta:
        model = Project
        fields = ['summary', 'description', 'users']


class AddProjectUsersForm(forms.ModelForm):
    users = forms.ModelMultipleChoiceField(queryset=User.objects.all(), required=False, label='Участники')

    class Meta:
        model = User
        fields = ['users']


class IssueProjectForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.projects = kwargs.pop('projects')
        print(self.projects)
        super().__init__(*args, **kwargs)
        self.fields['assigned_to'].queryset = User.objects.filter(teams__project__in=self.projects)

    class Meta:
        model = Issue
        exclude = ['create_date', 'project', 'created_by']


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=60, required=False, label='Поиск')

source/webapp/views/base_views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import TemplateView, View


class DetailView(TemplateView):
    context_key = 'objects'
    model = None
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        pk = kwargs.get(self.pk_url_kwarg)
        context = super().get_context_data(**kwargs)
        context[self.context_key] = get_object_or_404(self.model, pk=pk)
        return context


class UpdateView(View):
    template_name = None
    context_object_name = 'objects'
    pk_url_kwarg = 'pk'
    model = None
    class_form = None
    success_url = '/'

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        form = self.class_form(instance=obj)
        return render(request, self.template_name, {'form': form, self.context_object_name: obj})

    def post(self, request, *args, **kwargs):
        data = request.POST
        self.obj = self.get_object()
        form = self.class_form(instance=self.obj, data=data)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_object(self):
        pk = self.kwargs.get(self.pk_url_kwarg)
        obj = get_object_or_404(self.model, pk=pk)
        return obj

    def form_valid(self, form):
        form.save()
        return redirect(self.success_url)

    def form_invalid(self, form):
        return render(self.request, self.template_name, {'form': form, self.context_object_name: self.obj})


class DeleteView(View):
    model = None
    template_name = None
    confirm_template_name = None
    context_object_name = 'objects'
    success_url = '/'
    confirm_of_delete = None

    def get(self, request, pk):
        obj = get_object_or_404(self.model, pk=pk)
        return render(request, self.confirm_template_name, {self.context_object_name: obj})

    def post(self, request, pk):
        if self.confirm_of_delete and 'confirm' not in request.POST:
            return self.get(request, pk)
        elif 'confirm' in request.POST:
            return self.delete_object(pk)
        else:
            return self.delete_object(pk)

    def delete_object(self, pk):
        obj = get_object_or_404(self.model, pk=pk)
        try:
            obj.delete()
            return redirect(self.success_url)
        except BaseException as error:
            return render(self.request, self.template_name, {'errors': error})

source/webapp/views/issue_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.db.models import Q
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode

from webapp.models import Issue, PROJECT_STATUS_BLOCKED, Team, Project
from webapp.forms import IssueForm, SimpleSearchForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .base_views import DetailView


class IndexView(ListView):
    template_name = 'issue/index.html'
    context_object_name = 'issues'
    model = Issue
    ordering = ['-create_date']
    paginate_by = 4

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class IssueView(DetailView):
    template_name = 'issue/issue_detail.html'
    model = Issue
    context_key = 'issue'


class IssueCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'issue/create_issue.html'
    model = Issue
    form_class = IssueForm
    permission_required = 'webapp.add_issue'
    permission_denied_message = "Доступ запрещён"

    def get_form(self, form_class=None):
        form = super().get_form()
        username = self.request.user
        teams = Team.objects.filter(user__username__icontains=username)
        user_projects = []
        for team in teams:
            user_projects.append(team.project)
        form.fields['project'].queryset = Project.objects.filter(summary__in=user_projects).filter(status='active')
        return form

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('webapp:index')


class IssueUpdateView( UserPassesTestMixin, PermissionRequiredMixin, UpdateView):
    model = Issue
    class_form = IssueForm
    template_name = 'issue/update_issue.html'
    context_object_name = 'issue'
    fields = ['summary', 'description', 'status', 'type', 'project', 'assigned_to']
    permission_required = 'webapp.change_issue'
    permission_denied_message = "Доступ запрещён"

    def test_func(self):
        issue = self.get_object()
        project = issue.project
        teams = Team.objects.filter(project=project)
        users_id = []
        for team in teams:
            users_id.append(team.user.pk)
        return self.request.user.pk in users_id

    def get(self, request, *args, **kwargs):
        issue = self.get_object()
        if issue.project.status == PROJECT_STATUS_BLOCKED:
            raise Http404
        return render(request, 'issue/update_issue.html', {'form': self.class_form(instance=issue), self.context_object_name: issue})

    def get_object(self):
        issue_pk = self.kwargs.get('pk')
        return get_object_or_404(self.model, pk=issue_pk)

    def get_success_url(self):
        return reverse('webapp:index')


class IssueDeleteView(UserPassesTestMixin, PermissionRequiredMixin, DeleteView):
    model = Issue
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_issue'
    permission_denied_message = "Доступ запрещён"

    def get(self, request, *args, **kwargs):
        issue = self.get_object()
        if issue.project.status == PROJECT_STATUS_BLOCKED:
            raise Http404
        return render(request, 'issue/delete_issue.html', {'issue': issue})

    def test_func(self):
        issue = self.get_object()
        project = issue.project
        teams = Team.objects.filter(project=project)
        users_id = []
        for team in teams:
            users_id.append(team.user.pk)
        return self.request.user.pk in users_id

    def get_object(self):
        issue_pk = self.kwargs.get('pk')
        return get_object_or_404(self.model, pk=issue_pk)

source/webapp/views/status_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse
from webapp.models import Status
from webapp.forms import StatusForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView


class StatusView(ListView):
    template_name = 'status/status_list.html'
    context_object_name = 'statuses'
    model = Status
    ordering = 'name'


class StatusCreateView(LoginRequiredMixin, CreateView):
    template_name = 'status/create_status.html'
    model = Status
    form_class = StatusForm

    def get_success_url(self):
        return reverse('webapp:statuses_list')


class StatusUpdateView(LoginRequiredMixin, UpdateView):
    model = Status
    class_form = StatusForm
    template_name = 'status/update_status.html'
    context_object_name = 'status'
    fields = ['name']

    def get_success_url(self):
        return reverse('webapp:statuses_list')


class StatusDeleteView(LoginRequiredMixin, DeleteView):
    model = Status

    def get(self, request, *args, **kwargs):
        try:
            return self.delete(request, *args, **kwargs)
        except BaseException as error:
            return render(request, 'status/status_list.html', {'errors': error})

    def get_success_url(self):
        return reverse('webapp:statuses_list')

source/webapp/views/type_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse
from webapp.models import Type
from webapp.forms import TypeForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView


class TypeView(ListView):
    template_name = 'type/types_list.html'
    context_object_name = 'types'
    model = Type
    ordering = 'name'


class TypeCreateView(LoginRequiredMixin, CreateView):
    template_name = 'type/create_type.html'
    model = Type
    form_class = TypeForm

    def get_success_url(self):
        return reverse('webapp:types_list')


class TypeUpdateView(LoginRequiredMixin, UpdateView):
    model = Type
    class_form = TypeForm
    template_name = 'type/update_type.html'
    context_object_name = 'type'
    fields = ['name']

    def get_success_url(self):
        return reverse('webapp:types_list')


class TypeDeleteView(LoginRequiredMixin, DeleteView):
    model = Type

    def get(self, request, *args, **kwargs):
        try:
            return self.delete(request, *args, **kwargs)
        except BaseException as error:
            return render(request, 'type/types_list.html', {'errors': error})

    def get_success_url(self):
        return reverse('webapp:types_list')

source/webapp/templates/partial/confirm_of_delete.html
{% csrf_token %}
<h3 class="text-center text-danger">Подтвердите удаление?</h3>

<div class="mt-3 text-center">
    <input type="submit" value="Удалить" name="confirm" class="btn btn-danger">
    <a href="{{ url }}" class="btn btn-primary">Отмена</a>
</div>

source/webapp/templates/partial/issue_form.html
{% load widget_tweaks %}
{% csrf_token %}

{% for error in form.not_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p class="ml-3 mb-0"><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
    <p class="col-6 ml-0 d-inline-block">{{ field|add_class:'form-control' }}</p>
    {% for error in field.errors %}
        <small class="text-danger ml-3">{{ error }}</small>
    {% endfor %}
{% endfor %}

<p class="ml-3">
    <input type="submit" value="{{ button_text }}" class="btn btn-success">
    <button onclick="history.back();" class="btn btn-primary">Отмена</button>
</p>

source/webapp/templates/partial/pagination.html
<nav>
    <form action="" method="get">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page=1" tabindex="-1" aria-disabled="true">В начало</a>
            </li>
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}" tabindex="-1"
                       aria-disabled="true">Предыдущая</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" aria-disabled="false">Предыдущая</a>
                </li>
            {% endif %}
            <span class="current">
        </span>
            <li class="page-item">
               <p class="ml-5">Страница <input class="form-control w-25 d-inline-block" type="text" name="page" value="{{ page_obj.number }}" maxlength="3"> из {{ page_obj.paginator.num_pages }}</p>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">Следующая</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" aria-disabled="false">Следующая</a>
                </li>
            {% endif %}
            <li class="page-item">
                <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.paginator.num_pages }}">В конец</a>
            </li>
        </ul>
    </form>
</nav>

source/webapp/templates/partial/project_form.html
{% load widget_tweaks %}
{% csrf_token %}

{% for error in form.not_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
    <p>{{ field|add_class:'form-control' }}</p>
    {% for error in field.errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
{% endfor %}

<p class="text-center">
    <input type="submit" value="{{ button_text }}" class="btn btn-success">
    <a href="{% url 'webapp:projects_list' %}" class="btn btn-primary">Отмена</a>
</p>

source/webapp/templates/partial/project_list_partial.html
<li class="list-group-item d-flex justify-content-between align-items-center border-top-0">
    <a href="{% url 'webapp:project_detail' project.pk %}">{{ project }}</a>
    {% if user.is_authenticated %}
        <span class="badge badge-pill bg-light">
            {% if  perms.webapp.change_project %}
                <a href="{% url 'webapp:update_project' project.pk %}" class="btn text-info">Редактировать</a>
            {% endif %}
            {% if project.status == 'active' and perms.webapp.delete_project %}
                <form action="{% url 'webapp:delete_project' project.pk %}" method="GET" class="d-inline-block">
                {% csrf_token %}
                <button type="submit" class="btn text-danger">Удалить</button>
            </form>
            {% endif %}
        </span>
    {% endif %}

</li>

source/webapp/templates/partial/simple_search_form.html
{% load widget_tweaks %}

<form class="form-inline mb-3" action="" method="GET">
    <label for="{{ form.search.id_for_label }}" class="mr-2">{{ form.search.label }}:</label>
    {{ form.search|add_class:'form-control' }}
    <input type="submit" value="Найти" class="btn btn-success">
    {% for error in form.search.errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}
</form>

source/webapp/templates/partial/single_issue_display.html
<div class="alert alert-secondary">
    <div class="alert alert-success">
        <h5 class="mb-3">Задача: <span class="text-primary">{{ issue.summary }}</span></h5>
        <p class="mb-1"><b>Описание:</b> <span class="text-primary">{{ issue.description|linebreaks }}</span></p>
    </div>
    <table class="table table-borderless table-sm alert alert-info text-center">
        <thead>
        <tr>
            <th scope="col" class="pl-3">Дата создания</th>
            <th scope="col">Тип:</th>
            <th scope="col">Проект:</th>
            <th scope="col">Статус:</th>
            <th scope="col">Создатель:</th>
            <th scope="col">Исполнитель:</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="text-primary">{{ issue.create_date|date:'d.m.Y H:i:s' }}</td>
            <td class="text-primary">{{ issue.type }}</td>
            <td class="text-primary"><a href="{% url 'webapp:project_detail' issue.project.pk %}">{{ issue.project }}</a></td>
            <td class="text-primary">{{ issue.status }}</td>
            <td class="text-primary">{{ issue.created_by }}</td>
            <td class="text-primary">{{ issue.assigned_to }}</td>
        </tr>
        </tbody>
    </table>
</div>

source/webapp/templates/partial/status_form.html
{% load widget_tweaks %}

{% csrf_token %}
{{ form.name|add_class:"form-control col-6 offset-3" }}
<div class="text-center mt-3">
    <input type="submit" value="{{ value }}" class="btn btn-success">
    <a href="{% url 'webapp:statuses_list' %}" class="btn btn-primary">Отмена</a>
</div>

source/webapp/templates/partial/type_form.html
{% load widget_tweaks %}

{% csrf_token %}
{{ form.name|add_class:"form-control col-6 offset-3" }}
<div class="text-center mt-3">
    <input type="submit" value="{{ value }}" class="btn btn-success">
    <a href="{% url 'webapp:types_list' %}" class="btn btn-primary">Отмена</a>
</div>